version: '3.4'

services:
  appdb:
    image: postgres
 
  pgadmin:
    image: dpage/pgadmin4

  redis-db:
    image: redis
 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/Services/Auth/src/Auth.API/Dockerfile

  meals.api:
    image: ${DOCKER_REGISTRY-}mealsapi
    build:
      context: .
      dockerfile: src/Services/Meals/src/Meals.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/src/Users.API/Dockerfile

  posts.api:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: src/Services/Posts/src/Posts.API/Dockerfile
  
  comments.api:
    image: ${DOCKER_REGISTRY-}commentsapi
    build:
      context: .
      dockerfile: src/Services/Comments/src/Comments.API/Dockerfile

  follows.api:
    image: ${DOCKER_REGISTRY-}followsapi
    build:
      context: .
      dockerfile: src/Services/Follows/src/Follows.API/Dockerfile

  admin.api-gw:
    image: ${DOCKER_REGISTRY-}adminapigw
    build:
      context: .
      dockerfile: src/ApiGateways/src/AdminApiGw/Dockerfile

  web.api-gw:
    image: ${DOCKER_REGISTRY-}webapigw
    build:
      context: .
      dockerfile: src/ApiGateways/src/WebApiGw/Dockerfile

  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context: .
      dockerfile: src/ApiGateways/src/proxy/Dockerfile
      
volumes:
  appdb-data:
  redis-db-data: