version: '3.4'

services:
  appdb:
    image: postgres
 
  pgadmin:
    image: dpage/pgadmin4

  redis-db:
    image: redis
 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/Services/Auth/src/Auth.API/Dockerfile

  meals.api:
    image: ${DOCKER_REGISTRY-}mealsapi
    build:
      context: .
      dockerfile: src/Services/Meals/src/Meals.API/Dockerfile

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: src/Services/Category/src/Category.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/src/Users.API/Dockerfile

  posts.api:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: src/Services/Posts/src/Posts.API/Dockerfile

  # webapigw:
  #   image: ${DOCKER_REGISTRY-}webapigw
  #   build:
  #     context: .
  #     dockerfile: src/ApiGateways/src/WebApiGw/Dockerfile

  nginx-gw:
    image: ${DOCKER_REGISTRY-}nginx-gw
    build:
      context: .
      dockerfile: src/ApiGateways/src/nginx/Dockerfile
      
volumes:
  appdb-data:
  redis-db-data: